packages:
  - 'packages/*'
  - 'packages/config/*'
  - 'packages/core/*'
  - 'app'

catalog:
  axios: ^1.7.7
  eslint: ^9.13.0
  prettier: ^3.3.3
  stylelint: ^16.9.0
  typescript: ^5.6.2
  unbuild: ^2.0.0
  postcss-nesting: ^13.0.1
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  esno: ^4.8.0
  turbo: ^2.2.1
  vue: ^3.5.12
  vue-router: ^4.4.5
  unocss: ^0.65.2
  simple-git-hooks: ^2.11.1
  picocolors: ^1.1.1
  lint-staged: ^15.2.10
