packages:
  - 'packages/*'
  - 'packages/config/*'
  - 'packages/core/*'
  - 'app'

catalog:
  # repo
  turbo: ^2.5.0
  unbuild: ^3.5.0
  eslint: ^9.24.0
  prettier: ^3.5.3
  stylelint: ^16.18.0
  postcss: ^8.5.3
  esno: ^4.8.0
  simple-git-hooks: ^2.12.1
  lint-staged: ^15.5.1
  picocolors: ^1.1.1
  vitest: ^3.1.1
  '@vueuse/core': ^13.1.0
  '@types/node': ^22.14.1

  # app
  vue: ^3.5.13
  vue-router: ^4.5.0
  pinia: ^3.0.2
  element-plus: "^2.9.7"
  typescript: ^5.8.3
  axios: ^1.8.4
  unocss: ^66.0.0
  vite: "^6.3.1"
  vue-tsc: "^2.2.8"
  vite-plugin-vue-devtools: "^7.7.5"
  unplugin-auto-import: "^19.1.2"
  unplugin-vue-components: "^28.5.0"
  "@vitejs/plugin-vue": "^5.2.3"
